jpa:
  show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true
          
server:
  port: 8001
  servlet:
    context-path: ${APP_PATH}

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    enabled: ${SWAGGER_ENABLED}

