spring:
  application:
    name: product

  boot:
    admin:
      client:
        url: http://localhost:8062

server:
  port: 8002
  servlet:
    context-path: /product

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  info:
    env:
      enabled: true
