spring:
  application:
    name: product

server:
  port: 8002
  servlet:
    context-path: /product

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
