spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: /config-server-repo
          clone-on-start: true
          default-label: master

  security:
    user:
      name: amdin
      password: qwerty

server:
  port: 8888


